graphhopper:
  datareader.file: planet_79.47,12.654_80.736,13.46.osm.pbf

  graph.location: graph-cache

  import.osm.ignored_highways: footway,cycleway,path,pedestrian,steps

  profiles:
    - name: car
      vehicle: car
      weighting: custom
      custom_model:
        priority:
          - if: "road_access == DESTINATION"
            multiply_by: 0.1

  profiles_ch:
    - profile: car

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: localhost

  admin_connectors:
    - type: http
      port: 8990
      bind_host: localhost

  request_log:
    appenders: []