graphhopper:
  datareader.file: "planet_79.47,12.654_80.736,13.46.osm.pbf"
  graph.location: graph-cache

  profiles:
    - name: car
      custom_model_files: [car.json]

  profiles_ch:
    - profile: car

  profiles_lm: []

  graph.encoded_values: car_access, car_average_speed

  import.osm.ignored_highways: footway,cycleway,path,pedestrian,steps

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: localhost
  request_log:
    appenders: []
  admin_connectors:
    - type: http
      port: 8990
      bind_host: localhost